backend: github
  name: developerjahid/djdocs
  
media_folder: static/assets
public_folder: assets
  
collections:
  - name: doc
    label: Doc
    folder: doc
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }